#!/bin/bash
# Generated by depctl

set -euo pipefail

# Ensure we are in the project root
cd "$(dirname "$0")/../.."

TIMESTAMP=$(date +%Y%m%d%H%M%S)
BACKUP_DIR=".deploy/backups/$TIMESTAMP"

echo "💾 Creating backup in $BACKUP_DIR..."
mkdir -p "$BACKUP_DIR"

cp .deploy/docker-compose.yml "$BACKUP_DIR/"
if [ -f .deploy/.env ]; then
    cp .deploy/.env "$BACKUP_DIR/"
fi

# If there's a database, we should ideally dump it




echo "✅ Backup complete!"
